google_project_id       = "meta-map-315419"
google_bucket_name      = "ybbucket912"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"